name: All tests
on: push

jobs:
  test-setup:
    run-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      id: cache
      with:
        key: ${{ github.sha }}
        path: src/pygmid/version.py
    outputs:
      tests_already_run: ${{ steps.cache.outputs.cache-hit == true }}
  test:
    needs: test-setup
    if: needs.test-setup,outputs.test_already_run != true
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - run: pip install pytest .
    - run: python3 -m pytest tests/